hs.hotkey.bind({"cmd", "ctrl"}, "n", function()
  hs.application.launchOrFocus("Calendar")
end)
hs.hotkey.bind({"cmd", "ctrl"}, "j", function()
  hs.application.launchOrFocus("Google Chrome")
end)
hs.hotkey.bind({"cmd", "ctrl"}, "a", function()
  hs.application.launchOrFocus("Sidekick")
end)
hs.hotkey.bind({"cmd", "ctrl"}, "k", function()
  hs.application.launchOrFocus("iTerm")
end)
hs.hotkey.bind({"cmd", "ctrl"}, "l", function()
  hs.application.launchOrFocus("Emacs_mac")
end)
hs.hotkey.bind({"cmd", "ctrl"}, "v", function()
  hs.application.launchOrFocus("Visual Studio Code")
end)
hs.hotkey.bind({"cmd", "ctrl"}, ";", function()
  hs.application.launchOrFocus("Roam Research")
end)
hs.hotkey.bind({"cmd", "ctrl"}, "'", function()
  hs.application.launchOrFocus("Obsidian")
end)
hs.hotkey.bind({"cmd", "ctrl"}, "i", function()
  hs.application.launchOrFocus("Preview")
end)
hs.hotkey.bind({"cmd", "ctrl"}, "o", function()
  hs.application.launchOrFocus("Spotify")
end)
hs.hotkey.bind({"cmd", "ctrl"}, "z", function()
  hs.application.launchOrFocus("Zotero")
end)
