hs.hotkey.bind({"cmd", "ctrl"}, "h", function()
  hs.application.launchOrFocus("Calendar")
end)
hs.hotkey.bind({"cmd", "ctrl"}, "j", function()
  hs.application.launchOrFocus("Google Chrome")
end)
hs.hotkey.bind({"cmd", "ctrl"}, "k", function()
  hs.application.launchOrFocus("iTerm")
end)
hs.hotkey.bind({"cmd", "ctrl"}, "l", function()
  hs.application.launchOrFocus("Emacs_mac")
end)
hs.hotkey.bind({"cmd", "ctrl"}, ";", function()
  hs.application.launchOrFocus("Roam Research")
end)
